### ISSUE TITLE
add pyserial as requirement

### ISSUE THREAD

**Issue by mdiehm** [ndoornekamp/senseair_s8#1]
sth. like adding the following line to your setup.py:

`install_requires=['pysrial'],`

**Comment by ndoornekamp** [comment]
I'm not sure that's required - not too long ago I installed this package on a fresh Pi, and didn't need to install pyserial before being able to run this module. Did you have problems running it without installing pyserial first?

**Comment by mdiehm** [comment]
The standard Pi might be equipped with that package but it's for sure not a standard within a fresh python environment. I sure had to actually install the package first..
