### ISSUE TITLE
Sensor read command reads wrong register from sensor and can occasionally return invalid data.

### ISSUE THREAD

**Issue by Tyler-Ward** [ndoornekamp/senseair_s8#3]
The command used to talk to the S8 sensor looks to be reading an undocumented internal address on the sensor rather than the output data register. This can cause the returned value to occasionally contain an invalid value (In my case occasionally reporting ~16000).

When debugging I found some useful documentation at https://forum.airgradient.com/t/where-can-i-find-the-s8-documentation/292/5 where it lists the correct modbus command for reading the CO2 value as `0XFE, 0X04, 0X00, 0X03, 0X00, 0X01, 0XD5, 0XC5` (read 1 value from input register 3)

**Comment by Tyler-Ward** [comment]
Thanks for the fix, will switch to that branch rather than my localy modded version and will see if I see any more erronious values. Have been using a modded version with that command for a couple of weeks and havent seen an issue yet and the rest of the data has looked fine, however the error values were fairly uncommon (once every month or two with a 10s polling rate) so may take a while to be sure.

**Comment by ndoornekamp** [comment]
The change was merged and an updated package is now available from PyPi. Versions >= 0.0.10 will use the updated command
